name: Déploiement d'un serveur Git
  hosts: git_server
  become: true
  become_method: su

  tasks:
    - name: Installation de Git
      apt:
        name: git
        state: present

    - name: Création d'un utilisateur Git
      user:
        name: git
        shell: /bin/bash
        createhome: yes

    - #name: Configuration du serveur SSH
      #lineinfile:
        #path: /etc/ssh/sshd_config
        #line: 'AllowUsers git'
        #state: present
      #notify: Restart SSH

    - name: Redémarrage du service SSH
      service:
        name: sshd
        state: restarted
      become: true
      become_method: sudo
      become_user: root
      tags: Restart SSH

    - name: Initialisation du dépôt Git
      git:
        repo: /path/to/repo.git
        init: yes
        bare: yes
        user: git
        group: git

    - name: Configuration des autorisations du dépôt Git
      file:
        path: /path/to/repo.git
        owner: git
        group: git
        mode: '0700'
        recurse: yes

    - name: Création d'un fichier post-receive pour les hooks Git
      copy:
        src: files/post-receive
        dest: /path/to/repo.git/hooks/post-receive
        owner: git
        group: git
        mode: '0700'

    - name: Redémarrage du service Git
      systemd:
        name: git
        state: restarted