- name: Install Logstash
  hosts: machines
  become: true
  become_method: su
  tasks:
    - name: Import Logstash GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Logstash repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Install Logstash
      apt:
        name: logstash
        state: present
      become: true

    - name: Transférer le fichier de configuration Logstash
      copy:
        src: /ansible/elk/logstash.yml
        dest: /etc/logstash/logstash.yml
        owner: logstash
        group: logstash
        mode: "0644"

    - name: Start and Enable Logstash
      service:
        name: logstash
        state: started
        enabled: yes
      become: true
