apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop-db
  template:
    metadata:
      labels:
        app: prestashop-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: BASE64_ENCODED_PASSWORD
